<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<AssignMessage async="false" continueOnError="false" enabled="true" name="HPX_Fault_JSError">
    <DisplayName>Fault_JSError</DisplayName>
    <FaultRules/>
    <Properties/>
    <Set>
        <Headers/>
        <Payload contentType="application/json" variablePrefix="%" variableSuffix="#">
			{
				"resourceType":"OperationOutcome",
				"text":{
					"status":"generated",
					"div":"<div>
                <h1>Operation Outcome</h1>
                <table border="1">
                    <tr>
                        <td style="font-weight: bold;">Exception</td>
                        <td>[]</td>
                        <td>
                            <pre>Internal Error.</pre>
                        </td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
				},
				"issue":[
					{
						"severity":"error",
              			"code":"exception",              
						"details":"An unexpected internal error has occurred"
					}
				]
			}

            </Payload>
        <StatusCode>500</StatusCode>
        <ReasonPhrase>Internal Server Error</ReasonPhrase>
    </Set>
    <IgnoreUnresolvedVariables>true</IgnoreUnresolvedVariables>
</AssignMessage>
